stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/raw_avis/control1_stack.avi
      - data/raw_avis/control2_stack.avi
    outs:
      - data/preprocessed/control1_stack_normalized.npy
      - data/preprocessed/control2_stack_normalized.npy

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/preprocessed/control1_stack_normalized.npy
      - data/preprocessed/control2_stack_normalized.npy
    # outs:
    #   - model.pkl  # TODO: Uncomment this when we have actual model

  analyze:
    cmd: python analyze_data.py
    deps:
      - analyze_data.py
      - data/preprocessed/control1_stack_normalized.npy
      - data/preprocessed/control2_stack_normalized.npy
    outs:
      - analysis_results/data_info.json:
          cache: false
      - analysis_results/random_frames.png:
          cache: false
      - analysis_results/intensity_distribution.png:
          cache: false
