stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/raw_avis/control1_stack.avi
      - data/raw_avis/control2_stack.avi
    outs:
      - data/preprocessed/control1_stack_normalized.npy
      - data/preprocessed/control2_stack_normalized.npy

  split_data:
    cmd: python split_data.py
    deps:
      - split_data.py
      - data/preprocessed/control1_stack_normalized.npy
      - data/preprocessed/control2_stack_normalized.npy
    outs:
      - data/split/train_data.npy
      - data/split/val_data.npy
      - data/split/split_info.json

  analyze:
    cmd: python analyze_data.py
    deps:
      - analyze_data.py
      - data/split/train_data.npy
      - data/split/val_data.npy
    outs:
      - analysis_results/data_info.json:
          cache: false
      - analysis_results/random_frames.png:
          cache: false
      - analysis_results/intensity_distribution.png:
          cache: false

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/split/train_data.npy
      - data/split/val_data.npy
    # outs:
    #   - models/trained_model.pkl  # TODO: Uncomment when we have model
